port: 4141
host: localhost

Postgres:
  PG_POOL_MAX: 1
  PG_URL: postgres://root:1234@localhost:5434/postgres

Kafka:
  kafka_brokers: ["localhost:9092"]
  kafka_topic: orders

Cache:
  cache_ttl: 60m
  cache_check_interval: 30s